/* Shared bestiary prose for every form, including residents of older saves. */
var ENEMY_LORE = {
  rat:"A dungeon scavenger.",
  bat:"A small cave bat.",
  goblin:"A goblin armed with a stolen blade.",
  archer:"A goblin bowman.",
  brute:"An armored goblin brawler.",
  slime:"A stone-filled slime that spits sticky gravel.",
  shaman:"A goblin caster who heals and enrages allies.",
  skeleton:"An undead soldier.",
  mimic:"A predator disguised as a chest.",
  warchief:"Grukk, chief of the dungeon goblins.",
  emberling:"A small fire elemental.",
  tideling:"A small water elemental.",
  galeling:"A small air elemental.",
  stoneling:"A small earth elemental.",
  wisp:"A small shadow elemental.",
  lumenling:"A small light elemental.",
  shambler:"A shambling crypt corpse.",
  gravebeetle:"A crypt beetle that releases poison gas.",
  bonearcher:"An undead bowman.",
  shade:"A wandering shadow.",
  gravebloat:"A bloated corpse leaking poison gas.",
  acolyte:"A necromancer who protects undead allies.",
  morty:"Morty, the crypt's necromancer.",
  phylactery:"A vessel holding Morty's life force.",
  dawnsentinel:"Halves spell and ranged damage. Returns 4 damage on direct hits; your defenses apply.",
  halowisp:"A drifting light spirit.",
  prismscarab:"A beetle that splits its light beam between targets.",
  radiantwarden:"An armored guardian of the light realm.",
  stalker:"A shadow predator that ambushes from darkness.",
  gloommoth:"A moth that snuffs out light.",
  umbralhound:"A hound of the shadow realm.",
  nightwarden:"Guardian of the shadow gate.",
  burrower:"An armored tunneler.",
  crystalgolem:"A golem of living crystal.",
  mosstroll:"A regenerating troll covered in moss.",
  mountainheart:"A stone giant empowered by crystal nodes.",
  crystalnode:"A crystal that protects the Heart of the Mountain.",
  stormbeetle:"A cavern beetle charged with lightning.",
  sparkjelly:"A jelly filled with lightning.",
  shockeel:"An electric eel lurking in water.",
  myconid:"A mushroom creature of the Caverns.",
  shroomling:"A young myconid.",
  wormtender:"A myconid that tends the Deep Maw's tunnels.",
  crystalcrawler:"A crawler with a mineral shell.",
  caverat:"A large cavern rat.",
  cavebat:"A pale bat of the deep caverns.",
  caveslime:"A cavern slime that spits sticky gravel.",
  deepmaw:"A giant worm tunneling beneath the Caverns.",
  mawlimb:"Part of the Deep Maw.",
  cinderling:"A fire elemental of the Caverns.",
  rippleling:"A water elemental of the Caverns.",
  gustling:"An air elemental of the Caverns.",
  mossling:"An earth elemental of the Caverns.",
  duskling:"A shadow elemental of the Caverns.",
  gleamling:"A light elemental of the Caverns.",
  drowblade:"A drow duelist who waits in stealth.",
  drowpriestess:"A drow caster who heals and wards allies.",
  thoughteater:"A creature that feeds on minds.",
  webspitter:"A spider that fires webs.",
  spiderling:"A small Underdark spider.",
  drider:"A half-drow, half-spider warrior.",
  fireimp:"A fire-casting imp.",
  emberspider:"A spider with a burning bite.",
  matron:"Ruler of the Underdark's spider brood.",
  cinderimp:"An imp of the fire realm.",
  magmacrawler:"An armored crawler healed by fire.",
  flamedancer:"A spirit of living flame.",
  emberlord:"Ruler of the fire realm.",
  tidecrab:"A heavily armored crab.",
  siren:"A singer of the water realm.",
  drownedone:"An undead drowned traveler.",
  leviathaneel:"A giant eel of the water realm.",
  stormhawk:"A hawk charged with lightning.",
  thundertotem:"A storm-calling totem.",
  windwisp:"A wind spirit of the floating ruins.",
  tempestdjinn:"Ruler of the air realm.",
  'chaos-prism-seer':"A crystal-eyed caster of the Archives.",
  'chaos-folded-horror':"A warped creature of the Archives.",
  'chaos-rift-skitter':"A predator that moves through rifts.",
  'chaos-lens-bearer':"A support caster who shields allies and fires light beams.",
  'chaos-plague-bloat':"A plague-bearing creature of the Rot Hollows.",
  'chaos-brood-carrier':"A carrier of the Hollows' brood.",
  'chaos-bile-spitter':"A ranged bile-spitting creature.",
  'chaos-rotling':"A small creature of the Rot Hollows.",
  'chaos-horned-reaver':"An axe-wielding fighter of the Cinder Bastion.",
  'chaos-gorehound':"A hunting beast of the Cinder Bastion.",
  'chaos-ironbound':"A heavily armored Bastion fighter.",
  'chaos-chain-reaver':"A Bastion fighter wielding a hooked chain.",
  'chaos-lash-dancer':"A lash-wielding fighter of the violet courts.",
  'chaos-razor-dancer':"A duelist of the violet courts.",
  'chaos-silk-weaver':"A web-spinning creature of the violet groves.",
  'chaos-hookfang':"A fanged guardian of the silk warrens.",
  'unmaker-tyrant':"The Unmaker, ruler of Chaos.",
  'unmaker-unbound':"The Unmaker's unbound form.",
  'unmaker-heart':"The Unmaker's exposed heart.",
  shadowclone:"Your summoned shadow."
};
function enemyLore(entity){
  if(!entity)return '';
  return ENEMY_LORE[entity.kind]||(entity.base&&entity.base.lore)||'An unfamiliar creature.';
}
