/* Shared bestiary prose for every form, including residents of older saves. */
var ENEMY_LORE = {
  rat:"A whiskered scavenger grown bold on goblin scraps. It regards every abandoned boot as a possible meal.",
  bat:"A little hunter of the upper caves, guided by echoes through halls where daylight never reaches.",
  goblin:"A dungeon squatter with a stolen blade and grand ambitions. Most of those ambitions concern your pockets.",
  archer:"This goblin learned to hunt by shooting at things too large to argue with up close.",
  brute:"Well fed by goblin standards and proud of it. Its battered armor has outlasted several previous owners.",
  slime:"A patient puddle that gathers grit as it creeps. The stones inside it once belonged to the floor.",
  shaman:"Keeper of the tribe's charms, curses, and suspiciously glowing mushrooms. Even the other goblins give its staff a wide berth.",
  skeleton:"An old soldier still answering an order nobody living remembers. Dust spills from the joints of its borrowed armor.",
  mimic:"An excellent imitation of a treasure chest, right down to the inviting shine. The teeth are an unfortunate giveaway.",
  warchief:"Grukk won his throne through strength, cunning, and an unusually large collection of stolen furniture. He means to keep it.",
  emberling:"A scrap of living flame that escaped its hearth. It pops and crackles with the delight of being loose in the world.",
  tideling:"A wandering drop with a life of its own. Tiny currents turn beneath its rippling skin.",
  galeling:"A wayward puff of wind, forever curious about anything that might be blown over.",
  stoneling:"A pebble that woke one morning and decided to go somewhere. It has been taking its time ever since.",
  wisp:"A wandering blot of dusk, drawn to the warm edges of lamplight.",
  lumenling:"A small kindness of light made restless by the troubled elements. Its gentle glow hides a stubborn spirit.",
  shambler:"A forgotten resident of the crypt, roused from a sleep it plainly preferred. Earth and old grave-cloth trail behind it.",
  gravebeetle:"These glossy beetles thrive wherever the crypt's air turns stale. Their shells carry the colors of tarnished burial coins.",
  bonearcher:"The bow is warped and the quiver has rotted away, but the archer remembers its trade.",
  shade:"A memory that has forgotten the person it belonged to. It drifts through the crypt in search of something warm to remember.",
  gravebloat:"The crypt has been unkind to this swollen wanderer. An unhealthy green mist escapes the seams of its burial clothes.",
  acolyte:"An eager student of forbidden funerary arts. Its teachers have been dead for centuries, which hardly troubles the curriculum.",
  morty:"Morty has postponed his own funeral so often that the mourners stopped coming. He considers this proof of his success.",
  phylactery:"A carefully guarded vessel humming with a stolen lifetime. Something inside it refuses to rest.",
  dawnsentinel:"A watchman of the first sunrise, fashioned from pale stone and patient light. Its vigil has outlived the temple it served.",
  halowisp:"A drifting spark from the lamps of the celestial halls. It circles strangers with bright, unsettling curiosity.",
  prismscarab:"A jewel-backed beetle that gathers stray sunlight beneath its wings. Each movement scatters a little rainbow.",
  radiantwarden:"The old guardian of the luminous courts. Its shining mask has never learned to distinguish a pilgrim from an intruder.",
  stalker:"A shape glimpsed at the edge of a lantern's reach. Look directly at it, and the darkness seems empty again.",
  gloommoth:"A velvet-winged creature that drinks the glow from lamps. Its passing leaves a hush behind it.",
  umbralhound:"A hunter bred from the shadows of sleeping wolves. It follows the warmth of a heartbeat through the dark.",
  nightwarden:"The keeper of a gate no sunrise has ever found. Beneath its armor, the night itself appears to be moving.",
  burrower:"A tireless tunneler of the earthen realm. Its armored back is polished smooth by generations of stone.",
  crystalgolem:"A walking congregation of crystals, held together by an ancient purpose. Its footsteps ring like distant bells.",
  mosstroll:"A slow-growing guardian with a garden across its shoulders. It regards travelers as weeds in need of pulling.",
  mountainheart:"The mountain's oldest dream has taken a body of stone. The ground seems to listen whenever it stirs.",
  crystalnode:"A bright knot of the mountain's living power. Deep within it, a patient rhythm answers the surrounding stone.",
  stormbeetle:"A cavern beetle with thunder trapped beneath its shell. Sparks creep across its horns when it grows agitated.",
  sparkjelly:"A translucent drifter carrying a tiny storm in its body. Its soft blue glow makes a poor promise of safety.",
  shockeel:"A ribbon of muscle and bottled lightning lurking beneath the still water. Its eyes shine before the rest of it appears.",
  myconid:"A walking elder of the mushroom groves. Pale spores drift from its cap like the dust of a very old library.",
  shroomling:"A young sprout of the walking groves, all cap and enthusiasm. It hurries to follow the elders wherever they wander.",
  crystalcrawler:"A many-legged scavenger wearing the cavern's glittering minerals. Its shell chimes softly against the stone.",
  caverat:"Far below the surface, these rats have grown bold and broad. They know every crack in the cavern floor.",
  cavebat:"A pale bat of the deep grottoes. Generations without sunlight have taught it to trust the smallest echo.",
  caveslime:"A thick, dark ooze full of volcanic grit. It leaves the rock behind it oddly clean.",
  deepmaw:"An ancient hunger beneath the Caverns. Whole tunnels are said to be the tracks of its wandering.",
  mawlimb:"An ancient hunger beneath the Caverns. Whole tunnels are said to be the tracks of its wandering.",
  cinderling:"A hearth-spark grown wild in the deep earth. Its glow has hardened into the red heat of a banked forge.",
  rippleling:"A water spirit raised among underground pools. Rings spread across its surface even when the air is still.",
  gustling:"A restless draft given shape by the cavern's long passages. It carries the whisper of places far below.",
  mossling:"An earth spirit wearing a coat of soft cavern moss. Little stones tumble beneath it as it wanders.",
  duskling:"A deepening shadow that has learned to travel on its own. The edges of its body drink in the nearby light.",
  gleamling:"A glimmer grown bright among the cavern crystals. It shines with the stubborn warmth of a lantern kept alight through a long night.",
  drowblade:"A duelist from the Underdark's silk-hung courts. Every polished blade bears the mark of a rival's house.",
  drowpriestess:"A priestess entrusted with the spider court's most treasured secrets. Her whispered prayers set the overhead webs trembling.",
  thoughteater:"A pale dreamer drifting between minds. Its presence leaves the unsettling feeling that a familiar name has just been forgotten.",
  webspitter:"A watchful spider that tends its silk like a fisherman tends a net. Fresh threads gleam between its fangs.",
  spiderling:"A bright-eyed child of the hidden brood. Where one ventures, the rest are rarely far behind.",
  drider:"A sworn champion of the spider court, bearing both its people's pride and their goddess's unmistakable favor.",
  fireimp:"A gleeful little trespasser from a hotter world. It treats every curtain of webbing as an invitation.",
  emberspider:"A spider hatched beside the Underdark's molten seams. Tiny embers cling to the joints of its shell.",
  matron:"Mistress of the deepest silk halls, the Matron tends a kingdom spun from devotion and patient ambition. Every strand leads back to her.",
  cinderimp:"A quick-footed mischief-maker born from a shower of sparks. It never tires of finding something new to scorch.",
  magmacrawler:"A living seam of molten rock beneath a crusted shell. Orange light escapes whenever its heavy plates shift.",
  flamedancer:"A graceful spirit turning through an endless dance. Its flowing ribbons are tongues of living fire.",
  emberlord:"The crowned keeper of the fire realm's oldest furnace. Every coal in the hall seems to brighten at his approach.",
  tidecrab:"A great crab whose shell has weathered the turning of countless tides. Pearls and bits of shipwreck cling to its armor.",
  siren:"A singer of the drowned courts, weaving old sea-longing into every note. Even the currents lean closer to listen.",
  drownedone:"A lost traveler still reaching for a shore it can no longer remember. Water pours endlessly from its ragged sleeves.",
  leviathaneel:"An ancient sovereign of the sunless pools. Sailors tell stories of the wake it leaves in seas it has never visited.",
  stormhawk:"A proud hunter of the high winds, with lightning shining between its feathers. Thunder follows the beat of its wings.",
  thundertotem:"A weather-worn pillar raised to bargain with the sky. The storm has long since forgotten the terms.",
  windwisp:"A playful curl of wind with very little sense of a traveler's balance. It whistles through the floating ruins.",
  tempestdjinn:"A lord of wandering storms, robed in cloud and crowned in lightning. The winds gather to hear his next command.",
  'chaos-prism-seer':"A scholar of impossible futures, reading the world's fractures through a crown of crystal. Each eye watches a different tomorrow.",
  'chaos-folded-horror':"Something from the Archives has folded itself into a shape the world can almost hold. Its shadow suggests several missing limbs.",
  'chaos-rift-skitter':"A bright little predator that nests in the creases between places. The air wrinkles wherever it scurries.",
  'chaos-lens-bearer':"A devoted keeper of the Archives' wandering lights. It carries its great lens as carefully as a monk might carry a holy book.",
  'chaos-plague-bloat':"A lumbering gardener of the Rot Hollows. A whole damp ecosystem has made a home beneath its sagging hide.",
  'chaos-brood-carrier':"This wandering nursery shelters a squabbling brood in its folds. Every step is accompanied by squeaks and a puff of sour mist.",
  'chaos-bile-spitter':"A sour-tempered resident of the Hollows with a perpetually swollen throat. Nothing in its garden agrees with visitors.",
  'chaos-rotling':"A muddy little demon with an enormous appetite and no table manners. It leaves grubby fingerprints on everything it touches.",
  'chaos-horned-reaver':"A red-horned champion of the Cinder Bastion. It measures prestige by the dents in its axe and the challengers at its feet.",
  'chaos-gorehound':"A furnace-bred hunting beast that strains after every unfamiliar scent. Hot breath spills between its iron-colored fangs.",
  'chaos-ironbound':"A Bastion veteran enclosed in armor hammered shut long ago. Only the glow behind its visor betrays what still lives inside.",
  'chaos-chain-reaver':"A hunter of the Bastion's broken battlements. Its hooked chain drags a trail through the ash behind it.",
  'chaos-lash-dancer':"A dancer of the violet courts, stepping between silk curtains and their shadows. A jeweled lash keeps time with the music only she can hear.",
  'chaos-razor-dancer':"A violet-court duelist whose blades flash like silver ribbons. The audience is invisible, but every movement is a performance.",
  'chaos-silk-weaver':"A patient artisan of the violet groves. Its shining threads bind the floating ruins into a web of hidden pathways.",
  'chaos-hookfang':"A heavy-footed guardian of the silk warrens. Its curved fangs have worried their way through stone as readily as fallen branches.",
  'unmaker-tyrant':"The Unmaker wears a crown stolen from the order of things. From this broken throne, it would make the elements answer to a single will.",
  'unmaker-unbound':"The crown is broken, and the shape beneath it will no longer hold. Discord pours through the Unmaker like a storm through a shattered window.",
  'unmaker-heart':"At the center of the ruin beats a heart that cannot bear harmony. Its call reaches every lost corner of Chaos.",
  shadowclone:"A living echo cast by a passage through shadow. It wears a familiar face, but no light reaches its eyes."
};
function enemyLore(entity){
  if(!entity)return '';
  return ENEMY_LORE[entity.kind]||(entity.base&&entity.base.lore)||'A wandering creature drawn into these halls by the unrest of the elements.';
}
