/* Paused-floor timer metadata. Content owners retain creation, expiry and rules.
 * paid-turn is the saved action counter; world-clock is scheduler units, not
 * elapsed wall time or a normalized turn count. Travel only rebases these stamps.
 * Countdown fields (status.t, buffs, iceG/rootG/holyG/fireT) stay unchanged here.
 * Legacy records remain named so old saves keep the established resume policy. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FoteFloorClocks=api;})(globalThis,function(){
  'use strict';
  var records=[
    {"scope":"floor","path":["floorMeta","marks","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/planes/portals.js"},
    {"scope":"floor","path":["floorMeta","clouds","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/crypt/crypt.js"},
    {"scope":"floor","path":["floorMeta","dark","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/underdark/deepmobs.js"},
    {"scope":"floor","path":["floorMeta","shockClouds","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"floor","path":["floorMeta","tides","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/equipment/amulets.js"},
    {"scope":"floor","path":["floorMeta","upheaval","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/dungeon/beta-world.js"},
    {"scope":"floor","path":["floorMeta","hazardPending"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/planes/portals.js"},
    {"scope":"floor","path":["floorMeta","fwaPending"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/planes/planesfwa.js"},
    {"scope":"floor","path":["floorMeta","mortyReturn"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/crypt/crypt.js"},
    {"scope":"floor","path":["floorMeta","pendingLich"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/death-adapter.js"},
    {"scope":"floor","path":["floorMeta","maw"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"floor","path":["floorMeta","corpses","*"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/crypt/crypt.js"},
    {"scope":"floor","path":["floorMeta","regrow","*"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/presentation/render/vegart.js"},
    {"scope":"floor","path":["floorMeta","deathRemains","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/engine/death-adapter.js"},
    {"scope":"floor","path":["floorMeta","deathRemains","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/engine/death-adapter.js"},
    {"scope":"floor","path":["floorMeta","sporeFields","*"],"field":"armedTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/enemies/sporecaller.js"},
    {"scope":"floor","path":["floorMeta","sporeFields","*"],"field":"fireAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/sporecaller.js"},
    {"scope":"floor","path":["floorMeta","sporeFields","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/sporecaller.js"},
    {"scope":"floor","path":["floorMeta","greenTrail","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/green-slime.js"},
    {"scope":"floor","path":["floorMeta","greenTrail","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/green-slime.js"},
    {"scope":"floor","path":["floorMeta","greenTrail","*","packets","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/green-slime.js"},
    {"scope":"floor","path":["floorMeta","greenTrail","*","packets","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/green-slime.js"},
    {"scope":"floor","path":["floorMeta","webGround","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-fields.js"},
    {"scope":"floor","path":["floorMeta","webGround","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-fields.js"},
    {"scope":"floor","path":["floorMeta","magmaFlames","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-fields.js"},
    {"scope":"floor","path":["floorMeta","magmaFlames","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-fields.js"},
    {"scope":"floor","path":["floorMeta","smoke"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/elements/sigils.js"},
    {"scope":"floor","path":["floorMeta","sanctuary"],"field":"until","unit":"world-clock","pausedFloor":"rebase","owner":"js/faith/gods.js"},
    {"scope":"floor","path":["floorMeta","chaosCombat","hazards","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"floor","path":["floorMeta","chaosCombat","hazards","*"],"field":"expiresAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"floor","path":["floorMeta","chaosCombat"],"field":"lastPulse","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter"],"field":"majorReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter"],"field":"rushReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter"],"field":"summonReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter","warning"],"field":"armedTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter"],"field":"pylonPulseAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter","pylons","*"],"field":"readyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter","pylons","*","warning"],"field":"armedTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","unmakerEncounter","pylons","*","warning"],"field":"fireAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/unmaker-encounter.js"},
    {"scope":"floor","path":["floorMeta","matron"],"field":"nextRit","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/underdark/deepmobs.js"},
    {"scope":"floor","path":["floorMeta","matron","rit"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/underdark/deepmobs.js"},
    {"scope":"floor","path":["floorMeta","matron","venom"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/underdark/deepmobs.js"},
    {"scope":"floor","path":["floorMeta"],"field":"_arcTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"floor","path":["items","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/death-adapter.js, js/elements/capstones.js"},
    {"scope":"floor","path":["props","*"],"field":"until","unit":"paid-turn","pausedFloor":"rebase","owner":"js/equipment/amulets.js"},
    {"scope":"floor","path":["rooms","*"],"field":"cooledUntil","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/puzzles.js"},
    {"scope":"floor","path":["floorMeta","puzzles","*"],"field":"cooledUntil","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/puzzles.js"},
    {"scope":"floor","path":[],"field":"nextSpawn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/world.js, js/combat/systems.js"},
    {"scope":"actor","path":[],"field":"stormChargeAt","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"actor","path":[],"field":"stormReady","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"actor","path":[],"field":"sparkReady","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"actor","path":[],"field":"stoneImm","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/effect-adapter.js"},
    {"scope":"actor","path":[],"field":"caughtOff","unit":"paid-turn","pausedFloor":"rebase","owner":"js/enemies/enemy-perception.js"},
    {"scope":"actor","path":[],"field":"_surfT","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js, js/engine/actions-adapter.js"},
    {"scope":"actor","path":[],"field":"_burnedAt","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js, js/engine/actions-adapter.js"},
    {"scope":"actor","path":[],"field":"_fumeAt","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js, js/engine/actions-adapter.js"},
    {"scope":"actor","path":[],"field":"_shellTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js, js/engine/actions-adapter.js"},
    {"scope":"actor","path":[],"field":"_blockTurn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js, js/engine/actions-adapter.js"},
    {"scope":"actor","path":[],"field":"_hitKey","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/transitions.js (legacy compatibility)"},
    {"scope":"actor","path":[],"field":"_immuneMsg","unit":"paid-turn","pausedFloor":"rebase","owner":"js/engine/damage-adapter.js"},
    {"scope":"actor","path":["zap"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"actor","path":["grasp"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/biomes/crypt/crypt.js"},
    {"scope":"actor","path":["brand"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/planes/portals.js"},
    {"scope":"actor","path":["erupt"],"field":"at","unit":"paid-turn","pausedFloor":"rebase","owner":"js/world/planes/planesfwa.js"},
    {"scope":"actor","path":["pebbleSlam"],"field":"turn","unit":"paid-turn","pausedFloor":"rebase","owner":"js/combat/combat.js"},
    {"scope":"actor","path":["pebbleSlam"],"field":"at","unit":"world-clock","pausedFloor":"rebase","owner":"js/combat/combat.js"},
    {"scope":"actor","path":[],"field":"rallyUntil","unit":"world-clock","pausedFloor":"rebase","owner":"js/faith/gods.js"},
    {"scope":"actor","path":[],"field":"challengeUntil","unit":"world-clock","pausedFloor":"rebase","owner":"js/persistence/save.js (legacy compatibility)"},
    {"scope":"actor","path":[],"field":"waterPullReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/planes/planesfwa.js"},
    {"scope":"actor","path":[],"field":"sporeFieldReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/sporecaller.js"},
    {"scope":"actor","path":[],"field":"sporeSupportReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/sporecaller.js"},
    {"scope":"actor","path":[],"field":"rageReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-teamwork.js"},
    {"scope":"actor","path":[],"field":"teamSearchUntil","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-perception.js"},
    {"scope":"actor","path":[],"field":"searchUntil","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-perception.js"},
    {"scope":"actor","path":[],"field":"greenPulseAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/green-slime.js"},
    {"scope":"actor","path":[],"field":"brutePushReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/enemy-teamwork.js"},
    {"scope":"actor","path":[],"field":"skeletonChargeReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/enemies/skeleton-charge.js"},
    {"scope":"actor","path":[],"field":"chaosCooldown","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"actor","path":[],"field":"chaosDebuffReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"actor","path":[],"field":"chaosBeamReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/chaos/chaos-enemies.js"},
    {"scope":"actor","path":[],"field":"rootSpitReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/combat/combat.js"},
    {"scope":"actor","path":[],"field":"caveSpellReadyAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/world/biomes/caverns/cavernmobs.js"},
    {"scope":"actor","path":["st","*"],"field":"bornAt","unit":"world-clock","pausedFloor":"rebase","owner":"js/engine/effects.js"}
  ];
  records.forEach(function(record){Object.freeze(record.path);Object.freeze(record);});
  var actorSources=[['ents'],['floorMeta','pendingLich','entity'],['floorMeta','maw','ent']];
  actorSources.forEach(Object.freeze);
  return Object.freeze({records:Object.freeze(records),actorSources:Object.freeze(actorSources),
    units:Object.freeze(['paid-turn','world-clock']),pausedFloor:'rebase'});
});
